// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Vv6b01UesTOnFNRMmurGiMzfCjaDy6M',
    appId: '1:574980220198:android:0b22c372ffa2e1e60e4de7',
    messagingSenderId: '574980220198',
    projectId: 'expeditioner-39b43',
    storageBucket: 'expeditioner-39b43.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkfwi5EX3yylaShtvRXL7QgKpiyf_aGo',
    appId: '1:574980220198:ios:e64b991cc3a7d03f0e4de7',
    messagingSenderId: '574980220198',
    projectId: 'expeditioner-39b43',
    storageBucket: 'expeditioner-39b43.firebasestorage.app',
    iosClientId: '574980220198-hftcc519sm24jepfu3viulqrv62sns96.apps.googleusercontent.com',
    iosBundleId: 'com.expeditioneers.expeditioneerJournal',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2x5ydOb_MzERl32y1928brjBHe0FFVA',
    appId: '1:574980220198:web:ca70a6ba6b7e78680e4de7',
    messagingSenderId: '574980220198',
    projectId: 'expeditioner-39b43',
    authDomain: 'expeditioner-39b43.firebaseapp.com',
    storageBucket: 'expeditioner-39b43.firebasestorage.app',
    measurementId: 'G-H0R0DWZ4QL',
  );
}
